import os
from utils.constants import OUT_DIR,FIG_DIR

def describe_file(fname):
    """Return a friendly description for well-known output files."""
    if fname == "community_summary.csv":
        return "Summary statistics for each community detection method."
    elif fname == "nmi_similarity_matrix.csv":
        return "Pairwise Normalized Mutual Information (NMI) similarity matrix."
    elif fname.startswith("aligned_communities_") and fname.endswith(".csv"):
        return "Aligned communities (greedy Jaccard match) between two most similar methods."
    elif fname.endswith(".pdf"):
        return "PDF summary report with figures and tables."
    elif fname.endswith(".png") and "size_distribution" in fname:
        return "Histogram of community size distributions for all methods."
    elif fname.endswith(".png") and "nmi_similarity" in fname:
        return "Heatmap of NMI similarity matrix."
    elif fname.endswith(".png") and "aligned_communities_heatmap" in fname:
        return "Heatmap of top aligned communities for the two most similar methods."
    else:
        return ""

def publish_to_md(output_dir=OUT_DIR, fig_dir=FIG_DIR, md_file="output.md"):
    #md_filename = os.path.basename(md_file)
    #md_path = os.path.join(output_dir, md_filename)
    lines = []
    lines.append("# Analysis Outputs\n")
    lines.append("This document lists all key files generated by the analysis, with short descriptions and figures (where available).\n")

    # Output files
    lines.append("## Data Outputs (`output/`)\n")
    for fname in sorted(os.listdir(output_dir)):
        fpath = os.path.join(output_dir, fname)
        desc = describe_file(fname)
        lines.append(f"- **`{fname}`**: {desc if desc else ''}")
    lines.append("")

    # Figures
    lines.append("## Figures (`figures/`)\n")
    for fname in sorted(os.listdir(fig_dir)):
        if not fname.lower().endswith(('.png', '.jpg', '.jpeg')):
            continue
        fpath = os.path.join(fig_dir, fname)
        desc = describe_file(fname)
        lines.append(f"### {fname}")
        if desc:
            lines.append(f"*{desc}*")
        # Markdown image embedding
        lines.append(f"![{fname}]({fig_dir}/{fname})")
        lines.append("")

    # Write to output.md
    with open(md_file, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote Markdown summary to {md_file}")

if __name__ == "__main__":
    publish_to_md()
